name: Update Post Age

on:
  schedule:
    - cron: "0 0 * * 0" 
  workflow_dispatch:  

jobs:
  update-week:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update weeks in JS
        run: |
          file="index.html"   # Change if linkedInPost is in another file
        
          current=$(grep -oP '(?<=timeAgo: ")[0-9]+' "$file")
          next=$((current + 1))
          
          sed -i "s/timeAgo: \"${current} Weeks ago\"/timeAgo: \"${next} Weeks ago\"/" "$file"
          echo "Updated timeAgo: ${current} → ${next}"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update post age to ${next} Weeks ago [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
