name: Visitor Counter

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch visitor count
        run: |
          response=$(curl -s "https://api.countapi.xyz/hit/tsekajnr-portfolio/visits")
          count=$(echo $response | jq .value)
          echo "Visitors: $count"
          echo "$count" > visitors.txt

      - name: Update index.html
        run: |
          count=$(cat visitors.txt)
          file="index.html"

          # Replace placeholder VISITOR_COUNT in index.html
          sed -i "s/Visitor Count: [0-9]*/Visitor Count: ${count}/" "$file"

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update visitor count to ${count}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
